# Generated by Django 4.0 on 2021-12-11 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonData', models.FileField(blank=True, default='', upload_to='media')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userDatausername', to='auth.user')),
            ],
        ),
    ]
